Misc packaging/integration updates
SUSE-Enceladus/keg pull request #127
Opened 2023-03-24 12:15 UTC by jgleissner

A few packaging/integration related updates.

2023-03-27 13:57 UTC, rjschwei requested changes

2023-03-27 13:57 UTC, rjschwei commented on test/data/output/xml/config.kiwi
> +        <specification>KEG written image</specification>
s/written/generated/

2023-04-05 11:21 UTC, jgleissner commented
Ok to merge?

2023-04-05 11:45 UTC, rjschwei approved these changes

2023-04-05 11:45 UTC, merged